[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package"
version = "0.0.1"

dependencies = [
    "textual>=0.2.0",
]

[project.scripts]
princeton = "package:main"