on:
  push:
    branches:
      - main

jobs:
  hello:
    name: My first job
    runs-on: ubunto-latest
    steps:
      - name: My first job
        run: echo "Hello World!"
      - name: My second step
        run: mkdir -z test