name: Our CI

on:
  push:
  pull_request:
    branches:
      - main
      - other_branch
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install package
        run: python -m pip install .[test]
      - name: Run tests
        run: python -m pytest -v

      